### ISSUE TITLE
Turing Machine uses off-beat arrow, not in most fonts.

### ISSUE THREAD

**Issue by imneme** [ElijahCirioli/jsflap#1]
Students trying to build Turing Machines may find that the transition labels don't look right as the state arrows don't render correctly.  The arrow is U+1F826 ”Rightwards triangle-headed arrow with medium shaft”.  It renders for me only because I have the font `Julia Mono` installed.

This patch fixes the issue by using a similar-looking but broadly supported arrow:
```diff
diff --git a/javascript/automata/turing/turingTransition.js b/javascript/automata/turing/turingTransition.js
index 3fffd39..6904961 100644
--- a/javascript/automata/turing/turingTransition.js
+++ b/javascript/automata/turing/turingTransition.js
@@ -56,7 +56,7 @@ class TuringTransition extends PushdownTransition {
                const element = $(`
             <div class="tuple" tabindex="1">
                 <input type="text" spellcheck="false" maxlength="1" class="label-input read-input tuple-input">
-                <p class="tuple-delimeter">🠦</p>
+                <p class="tuple-delimeter">&rarr;</p>
                 <input type="text" spellcheck="false" maxlength="1" class="label-input write-input tuple-input">
                 <p class="tuple-delimeter">,&nbsp;</p>
                 <input type="text" spellcheck="false" maxlength="1" class="label-input move-input tuple-input">
```

**Comment by ElijahCirioli** [comment]
Thank you for catching this. This is a big oversight on my part, it actually effects Pushdown Automata as well. I will put out a fix shortly.

**Comment by ElijahCirioli** [comment]
Fixed in this commit: https://github.com/ElijahCirioli/jsflap/commit/d41b5c6e1699020771460f70c06469b75f62e86a

I don't really like the look of those arrow characters (which may be why I used this uncommon character in the first place), so I used the font awesome arrows that are used elsewhere in the UI.
